run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocyclo
    - gosec
    - bodyclose
    - sqlclosecheck

linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: ReviewAssigner
  gosec:
    excludes:
      - G115

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl

output:
  formats:
    - format: colored-line-number